#**Implemented By Muhammad Hanan Asghar**

#**Collecting Data**

In [1]:
from bs4 import BeautifulSoup
import requests

In [2]:
URL = "http://www.shayaribazar.com/"
html = requests.get(URL).content
soup = BeautifulSoup(html, "html.parser")

In [3]:
URLS = []
for li in soup.find("div", {"id":"demo1"}).findAll("li"):
  anchor = li.find("a").get("href")
  URLS.append(anchor)

In [5]:
data = []
for url in URLS:
  try:
    soup = BeautifulSoup(requests.get(url).content, "html.parser")
    link = soup.findAll("ul", class_="pagination")[0].findAll("li")[-2].find("a").get("href")
    data.append([link.split("=")[0], link.split("=")[-1]])
  except:
    pass

In [ ]:
file = open("data.txt", "w")
for i in data:
  for j in range(1, int(i[-1])+1):
    print("Scrapping --> ", i[0]+"="+str(j))
    soup = BeautifulSoup(requests.get(i[0]+"="+str(j)).content, "html.parser")
    for p in soup.findAll("div", class_="main_body_1"):
      file.write(p.find("p").text)
      file.write("\n")
file.close()

#**Preprocessing Data**

In [1]:
file = open('data.txt', 'r')
readit = file.readlines()

In [2]:
data = []
for i in readit[:2500]:
  data.append(i)

In [3]:
print("Number of Lines in Data:",len(data))

Number of Lines in Data: 2500


In [4]:
data = '.'.join(data)

In [5]:
data

'Na Sath Hai Kisi Ka Na Sahara Hai KoiNa Ham Hain Kisi Ke Na Hmara Hai Koi\n.Chehre ki hasi se har gam chupaoBahut kuchh bolo par kuchh na bataoKhud na rutho kabhi par sabko manaoYe raz hai zindagi ka, bas jeete jao\n.Phir se tere mehfil mein chala aya huAndaz wahi h bs alfaz naye laya huer kasz\n.Door rehne wale terko ek bat kehna chahta hu,agar mera khyal aaye to apna khyal rakhna\n.Pyar mein kisi ko khona bhi zindagi haiZindagi mein ghamo ka hona bhi zindagi haiYuh toh rehte hai hamare hontho par muskurahatPar chupke se kisi ke liye rona bhi zindagi hai\n.Saza hume ye kaisi mili dil lagane kiRo rahe magar tamnna thi muskurane kiApna dard kise dikhau aye dostDard bhi usine diya jo wajah thi muskurane ki…\n.ये झूठ है के मुहब्बत किसी का दिल तोड़ती हैलोग खुद ही टुट जाते है मुहब्बत करते-करते\n.Girte rahe hum sajdo me hasrat e ishQ ki khaatiragar ibadat e khuda me gire hote to zindgi jannat ban jati\n.Woh humsey apni marzi se baat krtey haiaur hum bhi kitney pagal hai ke unki marji ka int

In [6]:
data = data.replace('\ufeff','').replace('\n','').replace('\r','')

In [7]:
data

'Na Sath Hai Kisi Ka Na Sahara Hai KoiNa Ham Hain Kisi Ke Na Hmara Hai Koi.Chehre ki hasi se har gam chupaoBahut kuchh bolo par kuchh na bataoKhud na rutho kabhi par sabko manaoYe raz hai zindagi ka, bas jeete jao.Phir se tere mehfil mein chala aya huAndaz wahi h bs alfaz naye laya huer kasz.Door rehne wale terko ek bat kehna chahta hu,agar mera khyal aaye to apna khyal rakhna.Pyar mein kisi ko khona bhi zindagi haiZindagi mein ghamo ka hona bhi zindagi haiYuh toh rehte hai hamare hontho par muskurahatPar chupke se kisi ke liye rona bhi zindagi hai.Saza hume ye kaisi mili dil lagane kiRo rahe magar tamnna thi muskurane kiApna dard kise dikhau aye dostDard bhi usine diya jo wajah thi muskurane ki….ये झूठ है के मुहब्बत किसी का दिल तोड़ती हैलोग खुद ही टुट जाते है मुहब्बत करते-करते.Girte rahe hum sajdo me hasrat e ishQ ki khaatiragar ibadat e khuda me gire hote to zindgi jannat ban jati.Woh humsey apni marzi se baat krtey haiaur hum bhi kitney pagal hai ke unki marji ka intezar kartey hai.

In [8]:
import string
translator = str.maketrans(string.punctuation, ' '*len(string.punctuation)) #map punctuation to space
new_data = data.translate(translator)

In [9]:
new_data

'Na Sath Hai Kisi Ka Na Sahara Hai KoiNa Ham Hain Kisi Ke Na Hmara Hai Koi Chehre ki hasi se har gam chupaoBahut kuchh bolo par kuchh na bataoKhud na rutho kabhi par sabko manaoYe raz hai zindagi ka  bas jeete jao Phir se tere mehfil mein chala aya huAndaz wahi h bs alfaz naye laya huer kasz Door rehne wale terko ek bat kehna chahta hu agar mera khyal aaye to apna khyal rakhna Pyar mein kisi ko khona bhi zindagi haiZindagi mein ghamo ka hona bhi zindagi haiYuh toh rehte hai hamare hontho par muskurahatPar chupke se kisi ke liye rona bhi zindagi hai Saza hume ye kaisi mili dil lagane kiRo rahe magar tamnna thi muskurane kiApna dard kise dikhau aye dostDard bhi usine diya jo wajah thi muskurane ki… ये झूठ है के मुहब्बत किसी का दिल तोड़ती हैलोग खुद ही टुट जाते है मुहब्बत करते करते Girte rahe hum sajdo me hasrat e ishQ ki khaatiragar ibadat e khuda me gire hote to zindgi jannat ban jati Woh humsey apni marzi se baat krtey haiaur hum bhi kitney pagal hai ke unki marji ka intezar kartey hai 

In [10]:
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer
import pickle

In [11]:
!rm -rf '/content/tokenized_data.pkl'

In [12]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([new_data])

# saving the tokenizer for predict function.
pickle.dump(tokenizer, open('tokenized_data.pkl', 'wb'))

In [13]:
sequence_data = tokenizer.texts_to_sequences([new_data])[0]
vocab_size = len(tokenizer.word_index) + 1

In [14]:
print("Sequences Size:",len(sequence_data))
print("Vocabulary Size:",vocab_size)

Sequences Size: 75099
Vocabulary Size: 11958


In [15]:
sequences = []
for i in range(1, len(sequence_data)):
  words = sequence_data[i - 1 : i + 1]
  sequences.append(words)

In [16]:
print("Total Sequences:",len(sequences))

Total Sequences: 75098


In [17]:
import numpy as np
sequences = np.array(sequences)

In [18]:
X, Y = sequences[:, 0], sequences[:, 1]

In [19]:
X = np.array(X)
Y = np.array(Y)

In [20]:
from tensorflow.keras.utils import to_categorical

In [21]:
X[:10]

array([   6,  103,    1,   26,    9,    6,  550,    1, 2971,  221])

In [22]:
Y[:10]

array([ 103,    1,   26,    9,    6,  550,    1, 2971,  221,   17])

In [23]:
Y = to_categorical(Y, num_classes=vocab_size)

In [24]:
Y[:10]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding

In [48]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=1))
model.add(LSTM(1000, return_sequences=True))
model.add(LSTM(1000, return_sequences=True))
model.add(LSTM(512))
model.add(Dense(1000, activation="relu"))
model.add(Dense(vocab_size, activation="softmax"))

In [49]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 1, 10)             119580    
_________________________________________________________________
lstm_12 (LSTM)               (None, 1, 1000)           4044000   
_________________________________________________________________
lstm_13 (LSTM)               (None, 1, 1000)           8004000   
_________________________________________________________________
lstm_14 (LSTM)               (None, 512)               3098624   
_________________________________________________________________
dense_11 (Dense)             (None, 1000)              513000    
_________________________________________________________________
dense_12 (Dense)             (None, 11958)             11969958  
Total params: 27,749,162
Trainable params: 27,749,162
Non-trainable params: 0
__________________________________________

In [50]:
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.callbacks import ReduceLROnPlateau
from tensorflow.keras.callbacks import TensorBoard

checkpoint = ModelCheckpoint("poet_second.h5", monitor='loss', verbose=1,
    save_best_only=True, mode='auto')

reduce = ReduceLROnPlateau(monitor='loss', factor=0.2, patience=3, min_lr=0.0001, verbose = 1)

logdir='logsnextword1'
tensorboard_Visualization = TensorBoard(log_dir=logdir)

In [51]:
from tensorflow.keras.optimizers import Adam
model.compile(loss="categorical_crossentropy", optimizer=Adam(lr=0.001), metrics=['accuracy'])

In [52]:
print("Shape of Input Data:", X.shape)
print("Shape of Output Data:",Y.shape)

Shape of Input Data: (75098,)
Shape of Output Data: (75098, 11958)


In [ ]:
history = model.fit(X, Y, epochs=500, batch_size=200, callbacks=[checkpoint, reduce, tensorboard_Visualization])

In [59]:
from tensorflow.keras.models import load_model
cnn = load_model('poet.h5')

In [60]:
def generate_seq(model, tokenizer, enter_text, n_pred):
  in_text, result = enter_text, enter_text
  for _ in range(n_pred):
    encoded = tokenizer.texts_to_sequences([in_text])[0]
    encoded = np.array(encoded)
    yhat = model.predict_classes(encoded)
    out_word = ''
    for word, index in tokenizer.word_index.items():
      if index == yhat:
        out_word = word
        break
    in_text, result = out_word, result + ' '+ out_word
  return result

In [65]:
generate_seq(cnn, tokenizer, "Sath", 15)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


'Sath guzari shaam se pehle tha ki tarah se pehle tha ki tarah se pehle tha'